version: '3.7'

services:
  templateapi_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: templateapi_db
    #image: ${DOCKER_REGISTRY-}templateapi_db
    #build:
    #  context: ./db/
    #  dockerfile: Dockerfile


  templateapi:
    image: ${DOCKER_REGISTRY-}templateapi
    build:
      context: .
      dockerfile: TemplateApi/Dockerfile
      
volumes:
  db: