version: '3.9'

services:
  templateapi:
    image: ${DOCKER_REGISTRY-}templateapi
    build:
      context: .
      dockerfile: TemplateApi/Dockerfile
    depends_on:
      - db
  mssql-server:
    image: "mcr.microsoft.com/mssql/server"
