version: '3.4'

services:
  templateapi_db:
    ports:
      - "1433:1433"

  templateapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DATABASE_PASSWORD=abcDEF123#
      - DATABASE_DATASOURCE=locahlhost:1433
      - DATABASE_USERID=sa
      - DATABASE_INITIALCATALOG=template
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro