version: '3.9'

services:
  templateapi:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS=https: //+:443;http://+:80
      ConnectionStrings:TemplateString: "Server=db;Database=master;User=sa;Password=Your_password123;"
      #DbServer: "mssql-server"
      #DbPort: "1433"
      #DbUser: "SA"
      #Password: "Your_password123"
      #Database: "TemplateApi"
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro


  mssql-server:
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssqlvol:/var/opt/mssql/data 