name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

jobs:
  build:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      version: ${{ steps.get-version.outputs.version }}

    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: add git credentials
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Restore dependencies
      run: dotnet restore TemplateApi.sln
    - name: Build
      run: dotnet build TemplateApi.sln --no-restore
    - name: Test
      run: dotnet test TemplateApi.sln --no-build --verbosity normal

    - name: Add dotnet tool
      run: dotnet tool install --global Versionize
    - name: Versionize
      run: versionize
    - id: get-version
      run: versionize inspect
    
    - run: echo "${{steps.get-version.outputs.version}}"

    - name: git push changelog
      run: git push --follow-tags origin master

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Api Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./TemplateApi/Dockerfile
          push: true
          tags: flpinheiro/template_api:latest,flpinheiro/template_api:${{needs.build.outputs.version}}
